### ISSUE TITLE
Issue-close the windows head bar

### ISSUE THREAD

**Issue by satokihanada** [satokihanada/onelisten#16]
Automated Review Comments
Issues in src-tauri/tauri.conf.json:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in src/app/PlayerBar.tsx:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/app/layout.tsx:
  - (2, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/app/page.tsx:
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')

**Comment by martinjbrown776** [comment]
I got it.
