### ISSUE TITLE
Issue-use tauri v1

### ISSUE THREAD

**Issue by satokihanada** [satokihanada/onelisten#20]
Automated Review Comments
Issues in app.vue:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in package-lock.json:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
Issues in package.json:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in src-tauri/Cargo.lock:
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (196, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (282, 'Hardcoded string found')
  - (304, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (325, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (373, 'Line exceeds 80 characters')
  - (379, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (392, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (419, 'Line exceeds 80 characters')
  - (440, 'Hardcoded string found')
  - (467, 'Line exceeds 80 characters')
  - (475, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (482, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (506, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (538, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (567, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (592, 'Line exceeds 80 characters')
  - (595, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (609, 'Hardcoded string found')
  - (612, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (629, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (651, 'Hardcoded string found')
  - (652, 'Hardcoded string found')
  - (654, 'Hardcoded string found')
  - (655, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (672, 'Hardcoded string found')
  - (685, 'Hardcoded string found')
  - (696, 'Hardcoded string found')
  - (702, 'Hardcoded string found')
  - (703, 'Hardcoded string found')
  - (717, 'Hardcoded string found')
  - (723, 'Hardcoded string found')
  - (730, 'Hardcoded string found')
  - (738, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (756, 'Hardcoded string found')
  - (771, 'Hardcoded string found')
  - (775, 'Hardcoded string found')
  - (786, 'Hardcoded string found')
  - (795, 'Hardcoded string found')
  - (800, 'Hardcoded string found')
  - (807, 'Hardcoded string found')
  - (808, 'Hardcoded string found')
  - (820, 'Hardcoded string found')
  - (821, 'Hardcoded string found')
  - (834, 'Hardcoded string found')
  - (836, 'Hardcoded string found')
  - (848, 'Hardcoded string found')
  - (856, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (862, 'Hardcoded string found')
  - (868, 'Hardcoded string found')
  - (871, 'Hardcoded string found')
  - (873, 'Hardcoded string found')
  - (876, 'Hardcoded string found')
  - (877, 'Hardcoded string found')
  - (878, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (880, 'Hardcoded string found')
  - (891, 'Hardcoded string found')
  - (894, 'Hardcoded string found')
  - (896, 'Hardcoded string found')
  - (899, 'Hardcoded string found')
  - (900, 'Hardcoded string found')
  - (902, 'Hardcoded string found')
  - (909, 'Hardcoded string found')
  - (928, 'Hardcoded string found')
  - (934, 'Hardcoded string found')
  - (936, 'Hardcoded string found')
  - (937, 'Hardcoded string found')
  - (938, 'Hardcoded string found')
  - (941, 'Hardcoded string found')
  - (946, 'Hardcoded string found')
  - (948, 'Hardcoded string found')
  - (954, 'Hardcoded string found')
  - (955, 'Hardcoded string found')
  - (956, 'Hardcoded string found')
  - (966, 'Hardcoded string found')
  - (981, 'Hardcoded string found')
  - (988, 'Hardcoded string found')
  - (995, 'Hardcoded string found')
  - (1020, 'Hardcoded string found')
  - (1022, 'Line exceeds 80 characters')
  - (1033, 'Hardcoded string found')
  - (1046, 'Hardcoded string found')
  - (1052, 'Hardcoded string found')
  - (1061, 'Hardcoded string found')
  - (1063, 'Hardcoded string found')
  - (1064, 'Hardcoded string found')
  - (1065, 'Hardcoded string found')
  - (1071, 'Hardcoded string found')
  - (1081, 'Hardcoded string found')
  - (1086, 'Hardcoded string found')
  - (1093, 'Hardcoded string found')
  - (1098, 'Hardcoded string found')
  - (1099, 'Hardcoded string found')
  - (1102, 'Hardcoded string found')
  - (1112, 'Hardcoded string found')
  - (1117, 'Hardcoded string found')
  - (1123, 'Hardcoded string found')
  - (1129, 'Hardcoded string found')
  - (1133, 'Hardcoded string found')
  - (1136, 'Hardcoded string found')
  - (1149, 'Hardcoded string found')
  - (1153, 'Hardcoded string found')
  - (1166, 'Hardcoded string found')
  - (1171, 'Hardcoded string found')
  - (1177, 'Hardcoded string found')
  - (1182, 'Hardcoded string found')
  - (1184, 'Hardcoded string found')
  - (1185, 'Hardcoded string found')
  - (1187, 'Hardcoded string found')
  - (1189, 'Hardcoded string found')
  - (1190, 'Hardcoded string found')
  - (1191, 'Hardcoded string found')
  - (1196, 'Hardcoded string found')
  - (1208, 'Hardcoded string found')
  - (1211, 'Line exceeds 80 characters')
  - (1230, 'Hardcoded string found')
  - (1260, 'Hardcoded string found')
  - (1306, 'Hardcoded string found')
  - (1307, 'Hardcoded string found')
  - (1344, 'Hardcoded string found')
  - (1347, 'Hardcoded string found')
  - (1349, 'Hardcoded string found')
  - (1355, 'Hardcoded string found')
  - (1361, 'Hardcoded string found')
  - (1362, 'Hardcoded string found')
  - (1377, 'Hardcoded string found')
  - (1382, 'Hardcoded string found')
  - (1384, 'Line exceeds 80 characters')
  - (1387, 'Hardcoded string found')
  - (1394, 'Hardcoded string found')
  - (1396, 'Hardcoded string found')
  - (1397, 'Hardcoded string found')
  - (1411, 'Hardcoded string found')
  - (1417, 'Line exceeds 80 characters')
  - (1420, 'Hardcoded string found')
  - (1423, 'Hardcoded string found')
  - (1428, 'Hardcoded string found')
  - (1437, 'Hardcoded string found')
  - (1456, 'Hardcoded string found')
  - (1480, 'Line exceeds 80 characters')
  - (1502, 'Hardcoded string found')
  - (1508, 'Hardcoded string found')
  - (1511, 'Hardcoded string found')
  - (1514, 'Hardcoded string found')
  - (1516, 'Hardcoded string found')
  - (1518, 'Hardcoded string found')
  - (1519, 'Hardcoded string found')
  - (1523, 'Hardcoded string found')
  - (1527, 'Hardcoded string found')
  - (1530, 'Hardcoded string found')
  - (1535, 'Hardcoded string found')
  - (1542, 'Hardcoded string found')
  - (1546, 'Hardcoded string found')
  - (1552, 'Hardcoded string found')
  - (1553, 'Hardcoded string found')
  - (1559, 'Hardcoded string found')
  - (1566, 'Hardcoded string found')
  - (1574, 'Hardcoded string found')
  - (1576, 'Hardcoded string found')
  - (1586, 'Hardcoded string found')
  - (1605, 'Hardcoded string found')
  - (1606, 'Hardcoded string found')
  - (1623, 'Hardcoded string found')
  - (1635, 'Hardcoded string found')
  - (1636, 'Hardcoded string found')
  - (1638, 'Hardcoded string found')
  - (1649, 'Hardcoded string found')
  - (1650, 'Hardcoded string found')
  - (1666, 'Hardcoded string found')
  - (1667, 'Hardcoded string found')
  - (1673, 'Line exceeds 80 characters')
  - (1682, 'Hardcoded string found')
  - (1687, 'Hardcoded string found')
  - (1692, 'Hardcoded string found')
  - (1697, 'Hardcoded string found')
  - (1720, 'Hardcoded string found')
  - (1721, 'Hardcoded string found')
  - (1722, 'Hardcoded string found')
  - (1741, 'Hardcoded string found')
  - (1747, 'Line exceeds 80 characters')
  - (1750, 'Hardcoded string found')
  - (1757, 'Hardcoded string found')
  - (1770, 'Hardcoded string found')
  - (1775, 'Hardcoded string found')
  - (1813, 'Hardcoded string found')
  - (1823, 'Hardcoded string found')
  - (1824, 'Hardcoded string found')
  - (1828, 'Hardcoded string found')
  - (1830, 'Hardcoded string found')
  - (1831, 'Hardcoded string found')
  - (1836, 'Hardcoded string found')
  - (1837, 'Hardcoded string found')
  - (1839, 'Hardcoded string found')
  - (1840, 'Hardcoded string found')
  - (1841, 'Hardcoded string found')
  - (1842, 'Hardcoded string found')
  - (1845, 'Hardcoded string found')
  - (1849, 'Hardcoded string found')
  - (1851, 'Hardcoded string found')
  - (1852, 'Hardcoded string found')
  - (1855, 'Hardcoded string found')
  - (1859, 'Hardcoded string found')
  - (1870, 'Hardcoded string found')
  - (1875, 'Hardcoded string found')
  - (1876, 'Hardcoded string found')
  - (1877, 'Hardcoded string found')
  - (1883, 'Line exceeds 80 characters')
  - (1886, 'Hardcoded string found')
  - (1893, 'Hardcoded string found')
  - (1894, 'Hardcoded string found')
  - (1895, 'Hardcoded string found')
  - (1896, 'Hardcoded string found')
  - (1898, 'Hardcoded string found')
  - (1904, 'Hardcoded string found')
  - (1905, 'Hardcoded string found')
  - (1906, 'Hardcoded string found')
  - (1908, 'Hardcoded string found')
  - (1909, 'Hardcoded string found')
  - (1910, 'Hardcoded string found')
  - (1911, 'Hardcoded string found')
  - (1912, 'Hardcoded string found')
  - (1913, 'Hardcoded string found')
  - (1914, 'Hardcoded string found')
  - (1915, 'Hardcoded string found')
  - (1919, 'Hardcoded string found')
  - (1922, 'Hardcoded string found')
  - (1923, 'Hardcoded string found')
  - (1927, 'Hardcoded string found')
  - (1930, 'Hardcoded string found')
  - (1935, 'Hardcoded string found')
  - (1936, 'Hardcoded string found')
  - (1937, 'Hardcoded string found')
  - (1939, 'Hardcoded string found')
  - (1940, 'Hardcoded string found')
  - (1941, 'Hardcoded string found')
  - (1957, 'Hardcoded string found')
  - (1959, 'Hardcoded string found')
  - (1960, 'Hardcoded string found')
  - (1964, 'Hardcoded string found')
  - (1965, 'Hardcoded string found')
  - (1966, 'Hardcoded string found')
  - (1971, 'Hardcoded string found')
  - (1984, 'Hardcoded string found')
  - (1985, 'Hardcoded string found')
  - (1988, 'Hardcoded string found')
  - (1993, 'Hardcoded string found')
  - (1994, 'Hardcoded string found')
  - (1995, 'Hardcoded string found')
  - (1996, 'Hardcoded string found')
  - (1997, 'Hardcoded string found')
  - (2010, 'Hardcoded string found')
  - (2023, 'Hardcoded string found')
  - (2024, 'Hardcoded string found')
  - (2025, 'Hardcoded string found')
  - (2026, 'Hardcoded string found')
  - (2027, 'Hardcoded string found')
  - (2031, 'Hardcoded string found')
  - (2041, 'Hardcoded string found')
  - (2042, 'Hardcoded string found')
  - (2044, 'Hardcoded string found')
  - (2045, 'Hardcoded string found')
  - (2046, 'Hardcoded string found')
  - (2049, 'Hardcoded string found')
  - (2051, 'Hardcoded string found')
  - (2052, 'Hardcoded string found')
  - (2063, 'Hardcoded string found')
  - (2064, 'Hardcoded string found')
  - (2065, 'Hardcoded string found')
  - (2066, 'Hardcoded string found')
  - (2071, 'Hardcoded string found')
  - (2074, 'Hardcoded string found')
  - (2075, 'Hardcoded string found')
  - (2077, 'Hardcoded string found')
  - (2090, 'Hardcoded string found')
  - (2091, 'Hardcoded string found')
  - (2092, 'Hardcoded string found')
  - (2093, 'Hardcoded string found')
  - (2094, 'Hardcoded string found')
  - (2097, 'Hardcoded string found')
  - (2098, 'Hardcoded string found')
  - (2103, 'Hardcoded string found')
  - (2104, 'Hardcoded string found')
  - (2109, 'Hardcoded string found')
  - (2120, 'Hardcoded string found')
  - (2122, 'Hardcoded string found')
  - (2123, 'Hardcoded string found')
  - (2124, 'Hardcoded string found')
  - (2127, 'Hardcoded string found')
  - (2132, 'Hardcoded string found')
  - (2133, 'Hardcoded string found')
  - (2134, 'Hardcoded string found')
  - (2135, 'Hardcoded string found')
  - (2136, 'Hardcoded string found')
  - (2141, 'Hardcoded string found')
  - (2143, 'Hardcoded string found')
  - (2144, 'Hardcoded string found')
  - (2145, 'Hardcoded string found')
  - (2155, 'Hardcoded string found')
  - (2161, 'Hardcoded string found')
  - (2162, 'Hardcoded string found')
  - (2167, 'Hardcoded string found')
  - (2169, 'Line exceeds 80 characters')
  - (2171, 'Hardcoded string found')
  - (2172, 'Hardcoded string found')
  - (2173, 'Hardcoded string found')
  - (2174, 'Hardcoded string found')
  - (2184, 'Hardcoded string found')
  - (2190, 'Hardcoded string found')
  - (2194, 'Hardcoded string found')
  - (2195, 'Hardcoded string found')
  - (2202, 'Hardcoded string found')
  - (2209, 'Hardcoded string found')
  - (2224, 'Hardcoded string found')
  - (2227, 'Hardcoded string found')
  - (2230, 'Hardcoded string found')
  - (2243, 'Hardcoded string found')
  - (2246, 'Hardcoded string found')
  - (2251, 'Hardcoded string found')
  - (2260, 'Hardcoded string found')
  - (2278, 'Hardcoded string found')
  - (2290, 'Hardcoded string found')
  - (2293, 'Hardcoded string found')
  - (2294, 'Hardcoded string found')
  - (2295, 'Hardcoded string found')
  - (2296, 'Hardcoded string found')
  - (2298, 'Hardcoded string found')
  - (2299, 'Hardcoded string found')
  - (2300, 'Hardcoded string found')
  - (2311, 'Hardcoded string found')
  - (2317, 'Hardcoded string found')
  - (2367, 'Hardcoded string found')
  - (2371, 'Hardcoded string found')
  - (2377, 'Hardcoded string found')
  - (2378, 'Hardcoded string found')
  - (2380, 'Hardcoded string found')
  - (2404, 'Hardcoded string found')
  - (2413, 'Hardcoded string found')
  - (2473, 'Hardcoded string found')
  - (2498, 'Hardcoded string found')
  - (2533, 'Hardcoded string found')
  - (2546, 'Hardcoded string found')
  - (2547, 'Hardcoded string found')
  - (2549, 'Hardcoded string found')
  - (2558, 'Line exceeds 80 characters')
  - (2564, 'Hardcoded string found')
  - (2570, 'Hardcoded string found')
  - (2571, 'Hardcoded string found')
  - (2588, 'Hardcoded string found')
  - (2626, 'Hardcoded string found')
  - (2639, 'Hardcoded string found')
  - (2716, 'Line exceeds 80 characters')
  - (2728, 'Line exceeds 80 characters')
  - (2740, 'Line exceeds 80 characters')
  - (2752, 'Line exceeds 80 characters')
  - (2777, 'Line exceeds 80 characters')
  - (2790, 'Hardcoded string found')
  - (2794, 'Hardcoded string found')
  - (2799, 'Hardcoded string found')
  - (2803, 'Hardcoded string found')
  - (2808, 'Hardcoded string found')
  - (2817, 'Hardcoded string found')
  - (2818, 'Hardcoded string found')
  - (2821, 'Hardcoded string found')
  - (2822, 'Hardcoded string found')
  - (2824, 'Hardcoded string found')
  - (2825, 'Hardcoded string found')
  - (2826, 'Hardcoded string found')
  - (2827, 'Hardcoded string found')
  - (2829, 'Hardcoded string found')
  - (2831, 'Hardcoded string found')
  - (2832, 'Hardcoded string found')
  - (2833, 'Hardcoded string found')
  - (2834, 'Hardcoded string found')
  - (2837, 'Hardcoded string found')
  - (2838, 'Hardcoded string found')
  - (2843, 'Hardcoded string found')
  - (2849, 'Hardcoded string found')
  - (2850, 'Hardcoded string found')
  - (2851, 'Hardcoded string found')
  - (2870, 'Hardcoded string found')
  - (2875, 'Hardcoded string found')
  - (2877, 'Hardcoded string found')
Issues in src-tauri/Cargo.toml:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
Issues in src-tauri/src/main.rs:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in src-tauri/tauri.conf.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')

**Comment by martinjbrown776** [comment]
I got it.
